### ISSUE TITLE
cant install with the command 

### ISSUE THREAD

**Issue by GAMINGMarcellk** [mcdallas/cryptotools#42]
<string>:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rtgbgqaf\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rtgbgqaf\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rtgbgqaf\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rtgbgqaf\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-ugh8gx_x\cryptotools_8eb9764d665d4481a0088c4f43513499\cryptotools\__init__.py", line 16, in <module>
          _module = loader.find_module(module_name).load_module(module_name)
                    ^^^^^^^^^^^^^^^^^^
      AttributeError: 'FileFinder' object has no attribute 'find_module'
      [end of output]

**Comment by Lvceo** [comment]
Same here :
```
$ pip install git+https://github.com/mcdallas/cryptotools.git@master#egg=cryptotools
Defaulting to user installation because normal site-packages is not writeable
Collecting cryptotools
  Cloning https://github.com/mcdallas/cryptotools.git (to revision master) to /tmp/pip-install-ewf7a3w4/cryptotools_c2e5f3de8bd7462ca5336bb3f12c3ce6
  Running command git clone --filter=blob:none --quiet https://github.com/mcdallas/cryptotools.git /tmp/pip-install-ewf7a3w4/cryptotools_c2e5f3de8bd7462ca5336bb3f12c3ce6
  Resolved https://github.com/mcdallas/cryptotools.git to commit 9ba32c86af9590fec4da01b195f02e8004671f4c
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      /tmp/pip-install-ewf7a3w4/cryptotools_c2e5f3de8bd7462ca5336bb3f12c3ce6/setup.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ewf7a3w4/cryptotools_c2e5f3de8bd7462ca5336bb3f12c3ce6/setup.py", line 5, in <module>
          from cryptotools import __doc__ as docstring
        File "/tmp/pip-install-ewf7a3w4/cryptotools_c2e5f3de8bd7462ca5336bb3f12c3ce6/cryptotools/__init__.py", line 16, in <module>
          _module = loader.find_module(module_name).load_module(module_name)
                    ^^^^^^^^^^^^^^^^^^
      AttributeError: 'FileFinder' object has no attribute 'find_module'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
