### ISSUE TITLE
Can't install with python >= 3.12

### ISSUE THREAD

**Issue by mehdiirh** [mcdallas/cryptotools#45]
Command:
```bash
$ pip install git+https://github.com/mcdallas/cryptotools.git@master#egg=cryptotools
```

Output:
```bash
Collecting cryptotools
  Cloning https://github.com/mcdallas/cryptotools.git (to revision master) to /tmp/pip-install-ppciqcd9/cryptotools_2e5a6d4c29724c35badedf08182fa92b
  Running command git clone --filter=blob:none --quiet https://github.com/mcdallas/cryptotools.git /tmp/pip-install-ppciqcd9/cryptotools_2e5a6d4c29724c35badedf08182fa92b
  Resolved https://github.com/mcdallas/cryptotools.git to commit 9ba32c86af9590fec4da01b195f02e8004671f4c
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      <string>:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):
        File "/home/mehdi/python/projects/xray/xrayseller/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/mehdi/python/projects/xray/xrayseller/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mehdi/python/projects/xray/xrayseller/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-kpwr_z2x/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-kpwr_z2x/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-kpwr_z2x/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-kpwr_z2x/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
        File "/tmp/pip-install-ppciqcd9/cryptotools_2e5a6d4c29724c35badedf08182fa92b/cryptotools/__init__.py", line 16, in <module>
          _module = loader.find_module(module_name).load_module(module_name)
                    ^^^^^^^^^^^^^^^^^^
      AttributeError: 'FileFinder' object has no attribute 'find_module'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by mehdiirh** [comment]
this is still the case, any fixes ?
